Patients =
COUNTROWS(PatientSegments)

Segments =
DISTINCTCOUNT(PatientSegments[segment_id])

Observed Death Events =
SUM(PatientSegments[DEATH_EVENT])

Observed Death Event % =
DIVIDE(
    [Observed Death Events],
    [Patients]
)

Average Age =
AVERAGE(PatientSegments[age])

Average Ejection Fraction =
AVERAGE(PatientSegments[ejection_fraction])

Average Serum Creatinine =
AVERAGE(PatientSegments[serum_creatinine])

Diabetes Prevalence % =
100 * AVERAGE(PatientSegments[diabetes])

Hypertension Prevalence % =
100 * AVERAGE(PatientSegments[high_blood_pressure])

Selected Silhouette Score =
CALCULATE(
    MAX(ModelSelection[silhouette_score]),
    ModelSelection[selected] = 1
)
